### PR TITLE
Fix issue with get repo info #130

### LINKED ISSUE #80: output error while running the chain-bench scan
## Description

Executing this simple command: _docker run aquasec/chain-bench scan --repository-url [git repo] --access-token [git token]_

Produce these errors:
2022-07-28 03:44:50 INF 🚩      Fetch Starting
2022-07-28 03:44:50 ERR error in authenticated user data
2022-07-28 03:44:50 ERR error in fetching repository data
2022-07-28 03:44:50 INF 🛢️       Fetching Repository Settings Finished
2022-07-28 03:44:50 ERR error in fetching branch protection
2022-07-28 03:44:50 INF 🌱      Fetching Branch Protection Settings Finished
2022-07-28 03:44:50 ERR error in fetching workflows
2022-07-28 03:44:50 INF 🔧      Fetching Pipelines Finished
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb3f265]

goroutine 1 [running]:
github.com/aquasecurity/chain-bench/internal/scm-clients/clients.FetchClientData({0x0, 0x0}, {0x7fffb403df52?, 0x1?})
        /home/runner/work/chain-bench/chain-bench/internal/scm-clients/clients/clients.go:48 +0x3c5
github.com/aquasecurity/chain-bench/internal/commands.NewScanCommand.func1(0xc000242280?, {0xcfc484?, 0x2?, 0x2?})
        /home/runner/work/chain-bench/chain-bench/internal/commands/scan.go:22 +0xac
github.com/spf13/cobra.(*Command).execute(0xc000242280, {0xc00024c040, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000242000)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/aquasecurity/chain-bench/internal/commands.Execute({0xe4c9a8?, 0xc0000021a0?})
        /home/runner/work/chain-bench/chain-bench/internal/commands/root.go:21 +0x32
main.main()
        /home/runner/work/chain-bench/chain-bench/cmd/chain-bench/main.go:12 +0x27

### LINKED ISSUE #130: Issue when the sub group has the same name as the repository
## Description
Issue when the sub group has the same name as the repository.
Example: https://my-gitlab-instance.com/top-group/sub-group/repo-name/repo-name

getRepoInfo returns:
```
host: my-gitlab-instance.com
namespace: top-group/sub-group
repo: repo-name
err: %!s(<nil>)
```

## What did you expect to happen?
should return:
```
host: my-gitlab-instance.com
namespace: top-group/sub-group/repo-name
repo: repo-name
err: %!s(<nil>)
```

## What happened instead?
getRepoInfo returns:
```
host: my-gitlab-instance.com
namespace: top-group/sub-group
repo: repo-name
err: %!s(<nil>)
```

Made a PR for this but due to the contribution guidelines I created this issue as well.

### PR DESCRIPTION
**Pull request by codekuu**
## Description
Issue when the sub group has the same name as the repository.
The getRepoInfo function does not parse it out correctly.

This fixes this issue.

Example url: `https://my-gitlab-instance.com/top-group/sub-group/repo-name/repo-name`
getRepoInfo returned before:
```
host: my-gitlab-instance.com
namespace: top-group/sub-group
repo: repo-name
err: %!s(<nil>)
```

it now returns:
```
host: my-gitlab-instance.com
namespace: top-group/sub-group/repo-name
repo: repo-name
err: %!s(<nil>)
```

## Related issues
- Close #130
Might close:
- Close #80 

## Checklist
- [X] I've read the [guidelines for contributing](https://github.com/aquasecurity/chain-bench/blob/main/CONTRIBUTING.md) to this repository.
- [X] I've followed the [conventions](https://github.com/aquasecurity/chain-bench/blob/main/CONTRIBUTING.md#pull-requests) in the PR title.
- [X] I've added tests that prove my fix is effective or that my feature works.
- [N/A] I've updated the [readme](https://github.com/aquasecurity/chain-bench/blob/main/README.md) with the relevant information (if needed).
- [N/A] I've added usage information (if the PR introduces new options)
- [X] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by morwn — APPROVED** [review]

**Comment by codekuu** [comment]
mb, updated the test with correct BaseURL.

**Review by codekuu — COMMENTED** [review]
Updated the test, was the wrong BaseURL set for "github project under sub org with same name as repo"

File: internal/scm-clients/clients/clients_test.go [hunk 1]
```diff
@@ -45,6 +45,16 @@ func TestGetRepoInfo(t *testing.T) {
...
 		ExpectedErr: nil,
 		Expected:    RepoInfo{BaseUrl: "gitlab.com", Namespace: "rootgroup/subgroup/secondsubgroup", Project: "test"},
+	}, {
+		Name:        "gitlab project under sub group with same name as repo",
+		RepoUrl:     "https://gitlab.com/rootgroup/subgroup/secondsubgroup/secondsubgroup",
+		ExpectedErr: nil,
+		Expected:    RepoInfo{BaseUrl: "gitlab.com", Namespace: "rootgroup/subgroup/secondsubgroup", Project: "secondsubgroup"},
+	}, {
+		Name:        "github project under sub org with same name as repo",
+		RepoUrl:     "https://github.com/codekuu/suborg/secondsuborg/secondsuborg",
```
Comment (morwn) [inline internal/scm-clients/clients/clients_test.go:55]:
```suggestion
		RepoUrl:     "https://gitlab.com/codekuu/suborg/secondsuborg/secondsuborg",
```

File: internal/scm-clients/clients/clients_test.go [hunk 2]
```diff
@@ -45,6 +45,16 @@ func TestGetRepoInfo(t *testing.T) {
 		RepoUrl:     "https://gitlab.com/rootgroup/subgroup/secondsubgroup/test",
 		ExpectedErr: nil,
 		Expected:    RepoInfo{BaseUrl: "gitlab.com", Namespace: "rootgroup/subgroup/secondsubgroup", Project: "test"},
+	}, {
+		Name:        "gitlab project under sub group with same name as repo",
+		RepoUrl:     "https://gitlab.com/rootgroup/subgroup/secondsubgroup/secondsubgroup",
+		ExpectedErr: nil,
+		Expected:    RepoInfo{BaseUrl: "gitlab.com", Namespace: "rootgroup/subgroup/secondsubgroup", Project: "secondsubgroup"},
+	}, {
+		Name:        "github project under sub org with same name as repo",
```
Comment (morwn) [inline internal/scm-clients/clients/clients_test.go:54]:
```suggestion
		Name:        "gitlab project under sub org with same name as repo",
```

File: internal/scm-clients/clients/clients_test.go [hunk 3]
```diff
@@ -45,6 +45,16 @@ func TestGetRepoInfo(t *testing.T) {
...
+		RepoUrl:     "https://github.com/codekuu/suborg/secondsuborg/secondsuborg",
+		ExpectedErr: nil,
+		Expected:    RepoInfo{BaseUrl: "github.com", Namespace: "codekuu/suborg/secondsuborg", Project: "secondsuborg"},
```
Comment (morwn) [inline internal/scm-clients/clients/clients_test.go:57]:
```suggestion
		Expected:    RepoInfo{BaseUrl: "gitlab.com", Namespace: "codekuu/suborg/secondsuborg", Project: "secondsuborg"},
```

**Review by morwn — COMMENTED** [review]
Tests seem good, but target Github, and subgroups do not apply there. I added code suggestions to replace it to Gitlab, let me know if this is what you meant

**Comment by codekuu** [comment]
LGTM, accepted the changes

**Comment by morwn** [comment]
> LGTM, accepted the changes, added for github as well since It was the same problem their if a org had the same name as repo.

Hi, I don't see the tested you added for github

**Comment by codekuu** [comment]
> > LGTM, accepted the changes, added for github as well since It was the same problem their if a org had the same name as repo.
> 
> Hi, I don't see the tested you added for github

You are right, your changes did override them. Do you want me to add them again or should we ignore them?

**Review by morwn — APPROVED** [review]
